services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file: .env
    develop:
      watch:
        - path: .
          action: rebuild
  db:
    image: postgres:17.0-bookworm
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: