services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:17.0-bookworm
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}